### ISSUE TITLE
Mapa mental  Jeanette Arlet Salazar Nicolas

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Arlet04#1]
[Mapa mental WEB 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Arlet04/files/14671479/Mapa.mental.WEB.3.0.pdf)

**Comment by 27Fer12** [comment]
20/20 buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
